name: '.NET random pet name generator'
description: 'A Github action that creates an random pet name'
branding:
  icon: sliders
  color: purple
outputs:
  petname:
    description: 'The generated name.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  