name: '.NET random pet name'

on:
  push:
    branches: [ main, GitHubAction ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: .NET Random Pet Name
      id: generate-name
      uses: cyberbartels/random-pet@main #dotnet/samples/github-actions/DotNet.GitHubAction@main