name: '.NET random pet name'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: .NET Random Pet Name
      id: generate-name
      uses: cyberbartels/random-pet@GitHubAction #dotnet/samples/github-actions/DotNet.GitHubAction@main
    - name: Check result
      shell: bash
      run: |
        echo ${{ steps.generate-name.outputs.petname }}